Server:
  AppMode: debug # debug 开发环境, release 生产环境
  BackPort: ":8080" # 后台服务端口
  FrontPort: ":8180" # 前台服务端口
  UseMultipoint: true
Mysql:
  Host: "127.0.0.1"
  Port: 3306
  Config: ""
  Db: "gin_vue_db"
  User: root
  Password: "123456"   #Surface mysql psw
#  Password: lph991028 #DeskTop mysql psw
  Log_Level: error
JWT:
  TokenKey: lphBlogPlus
  Expire: 7d # 过期时间 (小时)
  Buffer: 1d
  Issuer: gin-vue-blog-demo
Redis:
  Enable: true
  DB: 7
  Addr: 127.0.0.1:6379
  Password: ""
Session:
  Name: mysession
  Salt: salt
  MaxAge: 600 # 秒
Upload:
  OssType: local # 控制存储: local、qiniu
  Path: public/uploaded # 本地文件访问路径 (OssType="local" 才生效)
  StorePath: public/uploaded # 本地文件上传路径 (OssType="local" 才生效)
  # Markdown 目前只支持本地上传 (目前使用前端导出, 该配置无效)
  MdPath: public/markdown/ # Markdown 访问路径
  MdStorePath: public/markdown/ # Markdown 上传路径
  ImageSize: 2
Email:
  Host: "smtp.163.com"       # 服务器地址, 例如 smtp.qq.com 前往要发邮件的邮箱查看其 smtp 协议
  Port: 465                  # 前往要发邮件的邮箱查看其 smtp 协议端口, 大多为 465
  From: ""     # 发件人 (邮箱)
  IsSSL: true                # 是否开启 SSL
  Secret: "" # 密钥, 不是邮箱登录密码, 是开启 smtp 服务后获取的一串验证码
  Nickname: ""           # 发件人昵称, 通常为自己的邮箱名
Captcha:
  SendEmail: true # 通过邮箱发送验证码
  ExpireTime: 15  # 过期时间 (分钟)
  Key-long: 6
  Img-Width: 240
  Img-Height: 80
  Open-Captcha: 0 # 0代表一直开启，大于0代表限制次数
  Open-Captcha-Timeout: 3600 # open-captcha大于0时才生效
Zap:
  Level: info
  Format: console
  Prefix: "[Gin-Vue-Blog]"
  Directory: log
  ShowLine: true
  LogInConsole: true
System:
  env: debug # Change to "develop" to skip authentication for development mode 11
  addr: 8888
  db-type: mysql
  oss-type: local # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-redis: false # 使用redis
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600
  #  路由全局前缀
  router-prefix: ""
